# dataMelanoma::create_data_project("2023-Glehr-NatCom")
proj_dir <- "data-raw/2023-Glehr-NatCom/"

# nolint start
# # # Data loaded from git@git.uni-regensburg.de:paper/2023-Glehr_rROC_code.git
# # # where it was generated by d03_analysis_02/src/setup_01_load_frontiers_10k.R
# # load(file.path(proj_dir, "data/cd4_cd8_relative.rda"))
# # load(file.path(proj_dir, "data/pheno_pops_10k.rda"))
# # load(file.path(proj_dir, "data/unique_validation_cd4_cd8_relative.rda"))
# data.table::fwrite(cd4_cd8_relative, file.path(proj_dir, "data/cd4_cd8_relative.csv"))
# data.table::fwrite(pheno_pops_10k, file.path(proj_dir, "data/pheno_pops_10k.csv"))
# data.table::fwrite(validation_cd4_cd8_relative, file.path(proj_dir, "data/unique_validation_cd4_cd8_relative.csv"))
# nolint end

#### 1. Download data
# TODO: download the data from figshare when it gets available
# dir.create(file.path(proj_dir, "data"), showWarnings = FALSE)
# download.file(
#     url = "https://figshare.com/ndownloader/files/42862243",
#     destfile = file.path(proj_dir, "data", "sim00_pure_estimate_node_counts_df.csv")
# )


#### 2. Read data
cd4_cd8_relative <- tibble::as_tibble(data.table::fread(
    file.path(proj_dir, "data", "cd4_cd8_relative.csv")
))
pheno_pops_10k <- tibble::as_tibble(data.table::fread(
    file.path(proj_dir, "data", "pheno_pops_10k.csv")
))
validation_cd4_cd8_relative <- tibble::as_tibble(data.table::fread(
    file.path(proj_dir, "data", "unique_validation_cd4_cd8_relative.csv")
))


#### 3. Save data in qrds format
qs::qsave(cd4_cd8_relative, file.path(proj_dir, "res", "cd4_cd8_relative.qs"))
qs::qsave(pheno_pops_10k, file.path(proj_dir, "res", "pheno_pops_10k.qs"))
qs::qsave(validation_cd4_cd8_relative, file.path(proj_dir, "res", "validation_cd4_cd8_relative.qs"))


#### 4. usethis::use_data()
glehr2023_cd4_cd8_relative <- cd4_cd8_relative
usethis::use_data(glehr2023_cd4_cd8_relative, overwrite = TRUE)

glehr2023_pheno_pops_10k <- pheno_pops_10k
usethis::use_data(glehr2023_pheno_pops_10k, overwrite = TRUE)

glehr2023_validation_cd4_cd8_relative <- validation_cd4_cd8_relative
usethis::use_data(glehr2023_validation_cd4_cd8_relative, overwrite = TRUE)
